// Snipcart API Key — auto-generated by Admin Dashboard
var PBS_SNIPCART_KEY = "MDQ0ZDg2YTQtNGJjNi00OWYxLTkxNTctZmNlMWJkZjJkNDgyNjM5MTc5OTUyNDY0MDkyMDEw";
document.querySelectorAll('#snipcart').forEach(function(el){el.setAttribute('data-api-key', PBS_SNIPCART_KEY);});
